### ISSUE TITLE
Sometimes the DTE doesn't show all errors

### ISSUE THREAD

**Issue by sagatowski** [tcunit/TcUnit-Verifier#20]
Sometimes the DTE does not include a category of errors (LOW, MEDIUM, HIGH, corresponding to message, warning and error) from the 'dte.ToolWindows.ErrorList.ErrorItems'. For some reason it's all or nothing within one category. This has been discovered while trying to include standard messages (INFO).

**Comment by Aliazzzz** [comment]
WEIRD, this seems to be a Beckhoff/VS.net specific issue

**Comment by sagatowski** [comment]
Yes, it's definitely a VS issue.

**Comment by sagatowski** [comment]
Solved in commit 246b3307f96c803b8d13c68e6322bed2013485ef.
Fixed by:
            dte.ToolWindows.ErrorList.ShowErrors = true;
            dte.ToolWindows.ErrorList.ShowMessages = true;
            dte.ToolWindows.ErrorList.ShowWarnings = true;
